name: S3_Mini_Build_V7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-setuptools python3-wheel libserialport-dev
          pip3 install empy==3.3.4 pexpect future

      - name: Download ESP32-S3 Toolchain
        run: |
          # S3 için gereken özel bıçak takımını direkt indiriyoruz
          wget https://github.com/espressif/crosstool-NG/releases/download/esp-12.2.0_20230208/xtensa-esp32s3-elf-12.2.0_20230208-x86_64-linux-gnu.tar.xz
          tar -xf xtensa-esp32s3-elf-12.2.0_20230208-x86_64-linux-gnu.tar.xz
          # Çekmecenin yerini robotun hafızasına kazı
          echo "$GITHUB_WORKSPACE/xtensa-esp32s3-elf/bin" >> $GITHUB_PATH

      - name: Configure
        run: |
          ./waf configure --board esp32s3devkit

      - name: Build Plane
        run: |
          ./waf plane

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: S3-Mini-ArduPlane-Firmware
          path: |
            build/esp32s3devkit/bin/ardplane.bin
            build/esp32s3devkit/bin/bootloader.bin
            build/esp32s3devkit/bin/partition-table.bin
